### ISSUE TITLE
Elixir completion would be the bomb

### ISSUE THREAD

**Issue by wakatara** [roxma/nvim-completion-manager#134]
Really loving ncm and it's been the easiest to get working on my nvim install (deoplete kept throwing errors) but it's working great for ruby, go, css, and python. However, I really really need Elixir, so was just wondering if anyone was working on that. 

I'd be more than willing to help out though not sure I'd be the best person to try to implement it from scratch though I do have dogma installed and working or my machine.

Great work though. Very happy with how nicely it works.

**Comment by wakatara** [comment]
Strangely, I have to admit even though its not on the home page documentation, autocompletion for Elixir and Phoenix appears to be included by me having alchemist (or vim-elixir) installed (though not sure which.). Is working great so far. :heart:

**Comment by wakatara** [comment]
So, I guess the only change I would say is changing the README.md to cover this off. I am happy to do that for you if you want.

**Comment by dkarter** [comment]
@wakatara I'm trying to get this working but no success so far. It is probably the only thing holding me from committing to NCM. Can you please share your dotfiles if you don't mind?

I'm hoping that by comparing your dotfiles to mine I'll be able to figure out how you made it work and then publish a PR for the README.md for this repo.

Thanks!

**Comment by wakatara** [comment]
Hey @dkarter !

Sure! This is my .vimrc (note I am using UltiSnips as well). 

https://gist.github.com/wakatara/52dee877afbee33f510f817629b7aa78

lemme know if I can be of any further help!
Daryl.

**Comment by RyanWarnock** [comment]
@dkarter Did you have any luck getting it to work? I'm not having any success with vim-elixir and alchemist installed.

**Comment by dkarter** [comment]
@RyanWarnock I did, but I am using a language server + NCM for that instead of alchemist. 

https://github.com/dkarter/dotfiles/blob/72d608c0462c92bcd21e8976d3011b4f39a9b41f/vimrc#L182

I'm using elixir-ls:

<img width="964" alt="image" src="https://user-images.githubusercontent.com/551858/36439597-130c2902-1633-11e8-85f3-f74e2a1c5ae0.png">

I had to "install" it manually to make it work - picture above shows you one of the tricks I used.
That along with the "Building and Running" section of elixir-ls where the key to making it work:

https://github.com/JakeBecker/elixir-ls#building-and-running

If you get stuck let me know. Good luck!
