### ISSUE TITLE
non-python sources

### ISSUE THREAD

**Issue by SevereOverfl0w** [roxma/nvim-completion-manager#20]
I noticed that https://github.com/roxma/nvim-completion-manager/blob/master/pythonx/cm_sources/cm_filepath.py

Is callback based in returning the completions. The registering is done via a python api though.

Is this an implementation detail, or can I write sources in other languages (in other plugins) that call the same underlying functions?

**Comment by roxma** [comment]
You can use any language, python3 is more preferable by this framework currently.

use the same protocol as [autoload/cm/sources/ultisnips.vim](https://github.com/roxma/nvim-completion-manager/blob/master/autoload/cm/sources/ultisnips.vim) `cm#sources#ultisnips#cm_refresh` function did.

If the completion calculation takes a while, you should call `cm#complete` later, through your own async channel, instead of in the same refresh handler function.

**Comment by roxma** [comment]
This is the registering code in pure vimscript:

```vim
au User CmSetup call cm#register_source({'name' : 'cm-ultisnips',
        \ 'priority': 7,  
        \ 'abbreviation': 'Snip',
        \ 'cm_refresh_patterns':['\S{1,}$'],
        \ 'cm_refresh': 'cm#sources#ultisnips#cm_refresh',
        \ })

" css
" the omnifunc pattern is PCRE
au User CmSetup call cm#register_source({'name' : 'cm-css',
        \ 'priority': 9,  
        \ 'scopes': ['css','scss'],
        \ 'abbreviation': 'css',
        \ 'cm_refresh_patterns':['\w{2,}$',':\s+\w*$'],
        \ 'cm_refresh': {'omnifunc': 'csscomplete#CompleteCSS'},
        \ })
```

**Comment by roxma** [comment]
I'll update the documentation for this, ask any question if you get confused.

**Comment by prabirshrestha** [comment]
Here is an example using asyncomplete that is written in vim script that uses job.

https://github.com/prabirshrestha/asyncomplete-tscompletejob.vim/blob/5eedc54022ffdc44fc1f4e7e13271ec19513a3a0/autoload/asyncomplete/sources/tscompletejob.vim
https://github.com/prabirshrestha/asyncomplete-gocode.vim/blob/93161392b82b42e36a78cdebdab32a9ea050fdff/autoload/asyncomplete/sources/gocode.vim

Since asyncomplete is fork of nvim-completion-manager you should be able to do the same. But as roxma mentioned vim script is single thread so you could still be blocked. I have been using the typescript asyncomplete job for a large codebase at work for at least a week and haven't noticed any lag.
