### ISSUE TITLE
How to disable auto selection in popup?

### ISSUE THREAD

**Issue by fannheyward** [roxma/nvim-completion-manager#46]
For example in x.py, when you typed `json.`, NCM will popup available function/class, and auto select `json._default_encoder`.

What I want is just open popup, is there anyway to disable the auto selection?

**Comment by Shougo** [comment]
```vim
set completeopt+=noinsert
```

**Comment by roxma** [comment]
`completeopt` is set internally by NCM.  You should not modify it when using this plugin. Check your vimrc whether there's autocmd setting this value.

**Comment by justinmk** [comment]
Why is `noselect` the default? And why does NCM modify user's completeopt at all?

**Comment by roxma** [comment]
@justinmk 

NCM's auto popup feature doesn't work with some settings of completeopt,  ` let g:cm_completeopt="menu,menuone"` for example.

I added a default setting `g:cm_completeopt="menu,menuone,noinsert,noselect"` so that NCM should just work regardless of user's `completeopt` set by the vimrc.

When NCM is enabled, `g:cm_completeopt` will override `completeopt`, you could modify it on your own risks.
