### ISSUE TITLE
Add preview to updated completeopt

### ISSUE THREAD

**Issue by SevereOverfl0w** [roxma/nvim-completion-manager#59]
This is the default in vim, seems like it should be the default here also.

Seems odd to be updating the completeopt in the first place, why is it done?

**Comment by roxma** [comment]
1. I disable it by default because it's personal preference, the preview window is kind of annoying.
2. The `completeopt` is set inside NCM by default is because NCM can not work well with `longest` or without `noinsert`.

I'll make this value configurable to fix 1, using a variable like `g:cm_completeopt`.

**Comment by roxma** [comment]
Add `let g:cm_completeopt="menu,menuone,noinsert,noselect,preview"` to your vimrc to enable the preview window.

There's no auto closing preview window feature currently. You might need something like `au CompleteDone * pclose`
